spring:
  application:
    name: parc-manager

  datasource:
    url: jdbc:postgresql://localhost:5432/parcmanager
    username: ${DB_USERNAME:parcmanager}
    password: ${DB_PASSWORD:parcmanager}

  flyway:
    enabled: true
    clean-disabled: false
    create-schemas: true
    locations: classpath:db/migration

  docker:
    compose:
      enabled: true
      file: "docker-compose.local.yml"
      skip:
        in-tests: true

dinotype:
  api:
    url: ${DINOTYPE_API_URL:http://localhost:8081}
